// Generated by dts-bundle-generator v9.3.1

import VtsConfig from 'types/config';
import { VtsField } from 'types/config';

declare abstract class ValidatorStatic {
	static getForm(form: string | HTMLFormElement): HTMLFormElement;
	static getField(name: string, form: HTMLFormElement): VtsField;
}
declare abstract class VtsStatic extends ValidatorStatic {
	static readonly version: string;
	static setDefaults(config: VtsConfig): void;
	static getFields(form: HTMLFormElement): NodeListOf<VtsField>;
	static getFieldGroup(field: VtsField): Array<VtsField | Element>;
}

export {};
